variable "terraform_template" { default = "poc-global.tf" }

variable "aws_profile" { description = "Enter profile for appropriate account - make sure to log in first!" }
variable "primary_region" { default = "us-west-2" }
variable "secondary_region" { default = "us-east-1" }

variable "app_cmdb_code" { }
variable "app_abbreviation" { }
variable "environment" { }
variable "use_case" { }

variable "bucket_prefixes" {
  type = "list"
  description = "List of 1 or more unique prefixes for buckets and KMS keys"
}

terraform {
  required_version = "> 0.11.0"
/* just use local state for POC purposes, unless sharing outputs
  backend "s3" {
    role_arn = "arn:aws:iam::025009383915:role/TerraformStateAndLocking-TerraformRole-1GNBRFA78DRM6"
    bucket = "fams-terraform-state-025009383915"
    region = "us-west-2"
    # If sharing & using remote state, change key to an appropriate value:
    #key = "mark-poc/terraform.tfstate"
    encrypt = true
    kms_key_id = "arn:aws:kms:us-west-2:025009383915:key/9b74e82b-3518-42d3-adcd-a816fd374996"
    dynamodb_table = "terraform-lock-table"
  }
*/
}

provider "aws" {
  version = "> 1.6"
  alias = "primary"
  region = "${var.primary_region}"
  profile = "${var.aws_profile}"
}
provider "aws" {
  version = "> 1.6"
  alias = "secondary"
  region = "${var.secondary_region}"
  profile = "${var.aws_profile}"
}

module "replicated_buckets" {
  source = "../"
  providers = {
    "aws" = "aws.primary"
    "aws.primary" = "aws.primary"
    "aws.secondary" = "aws.secondary"
  }
  app_cmdb_code = "${var.app_cmdb_code}"
  app_abbreviation = "${var.app_abbreviation}"
  environment = "${var.environment}"
  use_case = "${var.use_case}"

  bucket_prefixes = "${var.bucket_prefixes}"
}

# Get the CLI commands for replication generated by the module:
output "cli_primary_commands" { value = "${join("", formatlist("\n%s\n", module.replicated_buckets.primary_cli_commands))}" }
output "cli_secondary_commands" { value = "${join("", formatlist("\n%s\n", module.replicated_buckets.secondary_cli_commands))}" }